### ISSUE TITLE
Count and display JSON rpc error response codes

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/flood#15]
currently, flood or rather vegeta treats a JSON RPC `error` the same as a JSON RPC `result` because both are "successful" HTTP responses

for load tests, this can skew the final results, because if a node simply returns errors early and doesn't execute anything its throughput is of course higher.

I briefly looked at the vegate commands and report output, I'm not entirely sure where we can extract this but perhaps from the `attack_output`:

https://github.com/paradigmxyz/flood/blob/ea2ebab80db3747cb0f166015e4f88a6d1ac5e7c/flood/tests/load_tests/vegeta.py#L23-L29

it be great to have at least the number of rpc errors part of the test results object, ideally even the error messages itself.

**Comment by sslivkoff** [comment]
added a `--deep-check` option for load tests in 608eefe3cf2b053d04ad7af7820523df0d037752 inspects every response for valid result data

this mode is much slower so should be used sparingly
