### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by JonasPf** [paradigmxyz/flood#17]
**Version**

I'm using the `main` branch

**Platform**

`Darwin Q7Y7WJYHMX 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64`

**Description**

When creating a report I got:

```
No module named nbconvert
```

After installing `nbconvert` using `pip3 install nbconvert` I got:

```
jupyter_client.kernelspec.NoSuchKernel: No such kernel named python3
```

After installing `ipykernel` using `pip3 install ipykernel` it worked and I could create a report.

I believe the dependencies `ipykernel` and `nbconvert` are missing from `pyproject.toml`. Unfortunately my knowledge on Python packaging isn't up-to-date, therefore I didn't trust myself to create a useful PR for this problem.

**Comment by sslivkoff** [comment]
fixed in 5b195625f71526d7151310e8bc512d3d34d39749

I dont think ipykernel is necessary but if you run into problems feel free to re-open
