### ISSUE TITLE
Add tests for `eth_feeHistory`

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/flood#22]
**Is your feature request related to a problem? Please describe.**

To test the correctness of `eth_feeHistory` (and benchmark it) I would like to add an equality test for `eth_feeHistory`.

This involves:

1. Selecting a pivot block
2. Selecting an amount of blocks to query fee history for (`pivot - count` must not go outside finalized blocks, incl. genesis)
3. Optionally (that is, sometimes) generating some percentiles as floats from 0-100 (inclusive)

Blocked on https://github.com/checkthechain/checkthechain/issues/72

**Comment by sslivkoff** [comment]
added equality test here d67b6d2136f1cd14490171376775de7a64b38f20

still need a more detailed load test for `eth_feeHistory` tho

**Comment by sslivkoff** [comment]
added load test in 4bc0663f218dab14ed34256af2d8e8b0a6d7d671
