### ISSUE TITLE
Publish the Docker image to a public container registry

### ISSUE THREAD

**Issue by AndreMiras** [paradigmxyz/flood#23]
**Is your feature request related to a problem? Please describe.**
I want to try flood, but I'm lazy.
I wish I could simply `docker run --rm paradigmxyz/flood --help`.
But I don't want to git clone and build the Docker image myself.

**Describe the solution you'd like**
CI would push to a public container registry like the one provided by GitHub or DockerHub.

**Describe alternatives you've considered**
Of course I built, the image locally, it took me 3m60s and 1.6G
By the way we could leverage multistage build to make this image much much smaller.

**Additional context**
Thanks for providing the Dockerfile already, that was the hardest part.
By the way publishing to DockerHub can be as easy as simply pointing the DockerHub repository to this repository and it will automatically clone the code, build and publish without having to configure any CI. So rather than pushing from GitHub to DockerHub, you can pull the repo from DockerHub, this is pretty straight forward to configure

**Comment by sslivkoff** [comment]
done https://github.com/paradigmxyz/flood/pkgs/container/flood
