### ISSUE TITLE
Show the default for each flag in the help command

### ISSUE THREAD

**Issue by AndreMiras** [paradigmxyz/flood#27]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to see what's the default for each flag from within the help subcommand output.

**Describe the solution you'd like**
Something like the Python core argparse module has.

**Describe alternatives you've considered**
Alternatively we do get the actual value used in the run output, but ideally I'd like to know beforehand.
It could also be documented in the README.md

**Additional context**
argparse example, defaults documented in the help output:
https://docs.python.org/3/library/argparse.html
![image](https://github.com/paradigmxyz/flood/assets/24973/1df8d35f-fc61-421f-8eed-a32aac665919)

checkout action example, defaults documented in the README.md
https://github.com/actions/checkout
![image](https://github.com/paradigmxyz/flood/assets/24973/79d74d83-628b-414d-af1f-ba147ae7477d)

**Comment by sslivkoff** [comment]
fixed in ca80e9cbd521c31a932cc30099629a347e7884dc
