### ISSUE TITLE
Provide extra info to the report

### ISSUE THREAD

**Issue by AndreMiras** [paradigmxyz/flood#28]
**Is your feature request related to a problem? Please describe.**
I'd like the HTML report to provide extra essential infos for future records as we export the record to PDF for later reference.

**Describe the solution you'd like**
Extra infos such as:
- date of the report
- version of flood used
- version of dependencies used
- flood command used
- flood effective parameters used

**Describe alternatives you've considered**
Currently I'm editing the report manually to add a section before "Report Generation" with all this extra info.

**Additional context**
It would probably be OK to start simple and add the easy ones such as date and version, that would already be a good start to iterate over with the rest

**Comment by sslivkoff** [comment]
fixed in 453f5a4da4fdcbba9e881466445762d47a916250
