### ISSUE TITLE
Add flood --version

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/flood#36]
now that versions are enforced, 

> Exception: local version of flood 0.3.0a-dcf73c57 does not match remote version of flood 0.3.0a-c8974030

it would be useful to get version info via `flood --version`

**Comment by sslivkoff** [comment]
there is `flood version`. do you think it would be valuable to also have `flood --version`?

**Comment by mattsse** [comment]
Oh nice 
Can we add an Alias for --version as well?

**Comment by sslivkoff** [comment]
yea. will add

**Comment by sslivkoff** [comment]
added in 8e2cdc2499a6930ce75078842c458888f81db5d4
