### ISSUE TITLE
SSH connection doesn't work

### ISSUE THREAD

**Issue by D5ky** [paradigmxyz/flood#43]
**Version**
flood@flood-load-2:~$ pip list
Package                Version
---------------------- ----------------
aiohttp                3.8.5
aiosignal              1.3.1
aiosqlite              0.18.0
asttokens              2.2.1
async-timeout          4.0.3
attrs                  21.2.0
Automat                20.2.0
Babel                  2.8.0
backcall               0.2.0
bcrypt                 3.2.0
beautifulsoup4         4.12.2
bleach                 6.0.0
blinker                1.4
certifi                2020.6.20
chardet                4.0.0
charset-normalizer     3.2.0
checkthechain          0.3.9
click                  8.0.3
cloud-init             23.2.2
colorama               0.4.4
comm                   0.1.4
command-not-found      0.3
configobj              5.0.6
connectorx             0.3.2a6
constantly             15.1.0
contourpy              1.1.0
cryptography           3.4.8
cycler                 0.11.0
dbus-python            1.2.18
debugpy                1.6.7.post1
decorator              5.1.1
defusedxml             0.7.1
distro                 1.7.0
distro-info            1.1+ubuntu0.1
entrypoints            0.4
eth-abi-lite           3.2.0
executing              1.2.0
fastjsonschema         2.18.0
fonttools              4.42.1
frozenlist             1.4.0
httplib2               0.20.2
hyperlink              21.0.0
idna                   3.3
importlib-metadata     4.6.4
incremental            21.3.0
ipykernel              6.25.1
ipython                8.14.0
ipython-genutils       0.2.0
jedi                   0.19.0
jeepney                0.7.1
Jinja2                 3.0.3
jsonpatch              1.32
jsonpointer            2.0
jsonschema             3.2.0
jupyter_client         8.3.0
jupyter_core           5.3.1
jupyterlab-pygments    0.2.2
keyring                23.5.0
kiwisolver             1.4.4
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
loguru                 0.6.0
lxml                   4.9.3
markdown-it-py         3.0.0
MarkupSafe             2.0.1
matplotlib             3.7.2
matplotlib-inline      0.1.6
mdurl                  0.1.2
mistune                0.8.4
more-itertools         8.10.0
msgspec                0.14.2
multidict              6.0.4
nbclient               0.8.0
nbconvert              6.5.4
nbformat               5.9.2
nest-asyncio           1.5.7
netifaces              0.11.0
numpy                  1.23.5
oauthlib               3.2.0
orjson                 3.9.5
packaging              23.1
pandocfilters          1.5.0
paradigm-data-portal   0.2.2
paradigm-flood         0.3.0
parso                  0.8.3
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 10.0.0
pip                    22.0.2
platformdirs           3.10.0
polars                 0.17.15
prompt-toolkit         3.0.39
psutil                 5.9.5
psycopg                3.1.10
ptyprocess             0.7.0
pure-eval              0.2.2
pyarrow                12.0.1
pyasn1                 0.4.8
pyasn1-modules         0.2.1
pycryptodome           3.18.0
Pygments               2.16.1
PyGObject              3.42.1
PyHamcrest             2.0.2
PyJWT                  2.3.0
pyOpenSSL              21.0.0
pyparsing              2.4.7
pyrsistent             0.18.1
pyserial               3.5
python-apt             2.4.0+ubuntu2
python-dateutil        2.8.2
python-debian          0.1.43+ubuntu1.1
python-magic           0.4.24
pytz                   2022.1
PyYAML                 5.4.1
pyzmq                  25.1.1
requests               2.25.1
rich                   13.5.2
SecretStorage          3.3.1
service-identity       18.1.0
setuptools             59.6.0
six                    1.16.0
sos                    4.4
soupsieve              2.4.1
ssh-import-id          5.11
stack-data             0.6.2
systemd-python         234
tinycss2               1.2.1
toml                   0.10.2
toolcli                0.6.16
toolconf               0.1.2
tooljob                0.1.6
toolplot               0.3.5
toolsql                0.6.2
toolstr                0.9.7
tooltime               0.2.11
tornado                6.3.3
tqdm                   4.66.1
traitlets              5.9.0
Twisted                22.1.0
typing_extensions      4.7.1
ubuntu-advantage-tools 8001
ubuntu-drivers-common  0.0.0
ufw                    0.36.1
unattended-upgrades    0.1
urllib3                1.26.5
wadllib                1.3.6
wcwidth                0.2.6
webencodings           0.5.1
wheel                  0.37.1
xkit                   0.0.0
yarl                   1.9.2
zipp                   1.0.0
zope.interface         5.4.0

**Platform**
Ubunu 22.04

**Description**
I think this changes broke ssh function https://github.com/paradigmxyz/flood/issues/36 

```
$ flood eth_getBlockByNumber server1=flood@1.1.1.1:my.host server2=flood@1.1.1.1:my.host --rates 2 2 2 --duration 5 --save-raw-output --output ~/flood
┌─────────────────────────────────┐
│ Load test: eth_getBlockByNumber │
└─────────────────────────────────┘
- sample rates: [2, 2, 2]
- sample duration: 5
- extra args: None
- output directory: /root/flood

Gathering node data...
──────────────────────
[WARNING] ctc config file does not exist; use `ctc setup` on command line to generate a config file

         node  │                                     url  │        metadata
    ───────────┼──────────────────────────────────────────┼──────────────────
               │                                          │            Geth
      server1  │                     flood@1.1.1.1  │  v1.9.10-stable
               │  https://my.host  │     linux-amd64
               │                                          │        go1.19.4
    ───────────┼──────────────────────────────────────────┼──────────────────
               │                                          │            Geth
      server2  │                    flood@1.1.1.1  │  v1.9.10-stable
               │  https://my.host  │     linux-amd64
               │                                          │        go1.19.4


Running load tests...
─────────────────────
[2023-08-22 17:10:11] Starting
Process Process-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/flood/tests/load_tests/load_test_runs.py", line 179, in run_load_test
    result = _run_load_test_remotely(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flood/tests/load_tests/load_test_runs.py", line 308, in _run_load_test_remotely
    remote_flood_version = remote_installation['flood_version']
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/flood/tests/load_tests/load_test_runs.py", line 179, in run_load_test
    result = _run_load_test_remotely(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flood/tests/load_tests/load_test_runs.py", line 308, in _run_load_test_remotely
    remote_flood_version = remote_installation['flood_version']
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'int' object is not subscriptable
```
[Source](https://github.com/paradigmxyz/flood/blob/61644933f9d822e4497f278f361649798088e3dc/flood/tests/load_tests/load_test_runs.py#L308C28-L308C47) 

`flood@1.1.1.1:my.host` is fake data for public, my hosts work and commands like ssh and ping working from my server.

This is response from my other server, returns versions as integer (?), and [python code expect boolean](https://github.com/paradigmxyz/flood/commit/8e2cdc2499a6930ce75078842c458888f81db5d4#diff-9a52085c95a4043ca5d941252737fab80aef2ec05365e9a96a316fc9dd59a6a1R29)? 
```
flood@load-flood-1:~$ flood --version
1
flood@load-flood-1:~$ python3 -m flood version --json
1
```

this command from my main server returns 1 too
```
$ ssh flood@my.host bash -c 'source ~/.profile; echo $(python3 -m flood version --json)'
/home/flood/.profile: line 1: source: filename argument required
source: usage: source filename [arguments]
1
```

**Comment by sslivkoff** [comment]
Hi. I believe this is fixed in 0.3.1. please reinstall on both the local and remote machines with `pip install -U paradigm-flood`. If that doesnt work we'll reopen the issue
