### ISSUE TITLE
Can we document better default output for flood results?

### ISSUE THREAD

**Issue by Aracki** [paradigmxyz/flood#48]
<img width="411" alt="image" src="https://github.com/paradigmxyz/flood/assets/6129986/eb7a0c08-ec87-42df-9cb7-9e7fbd383f65">

These summaries like `success vs load`, `throughput vs load` & `p90 vs load` are misleading. I don't really understand what does that mean.

**Comment by sslivkoff** [comment]
what command did you use to run flood? did you give the nodes names or are those just the placeholders that you need to replace with actual names?

**Comment by Aracki** [comment]
```
flood eth_getStorageAt NODE1_NAME=https://eth.merkle.io NODE2_NAME=https://rpc.ankr.com/eth --rates 1000 --duration 30
```
<img width="454" alt="image" src="https://github.com/paradigmxyz/flood/assets/6129986/160d7a9e-a276-4920-82f1-b2a34e7fe14a">

This is what I'm getting now, but I'm completely perplexed what each number meant.

**Comment by sslivkoff** [comment]
the (unit) above each column tells what units are being used

so this is saying, when you apply a load of 1000 requests per second (rps),  you get a p90 latency of .389 seconds

the throughput units looks like a typo, it should be (rps)

**Comment by Aracki** [comment]
Oh, maybe I was confused by `vs load` part in each column. I get it now.

But what represent `throughput` in seconds then?

**Comment by Aracki** [comment]
I guess it should represent how much requests has passed and "success" means percentage (0-1) of passed.

But strange fact is that for a lot of public nodes, this number is close to 0 🤔

**Comment by Aracki** [comment]
thanks for answers anyway. 

I propose you change it to:
`success ratio`, `rps` and `p90` without `vs load` part. It would be clear from the first glance I'd say.
