### ISSUE TITLE
About in-function imports.

### ISSUE THREAD

**Issue by hkey0** [paradigmxyz/flood#53]
I saw that some modules are imported inside functions. Is there a reason for this? Or is it a complete error? If it is a bug, I will send a PR to fix all the imports I see.

Thank you, have a good day.

**Comment by sslivkoff** [comment]
lazy imports are a performance optimization to improve responsiveness of python cli tools

in python, import times can actually be quite substantial. delaying those imports to if/when they are actually use improves startup times. startup times are particularly important for cli tools, not so much in other types of tools
