### ISSUE TITLE
Tests should treat connection errors as failures

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/flood#7]
the purpose of the equality tests is to compare results from two different endpoints.

It currently treats connectivity errors as equal:

> HTTPSConnectionPool(host='', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105492950>: Failed to establish a new connection: [Errno 61] Connection refused'))
HTTPSConnectionPool(host='', port=8545): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1002)')))

which would result in no differences

**Comment by sslivkoff** [comment]
fixed in `fbb6b092`
